AWSTemplateFormatVersion: '2010-09-09'
Description: 'person-poc

  Rest API to manage a Data Lake of person links

  '
Globals:
  Function:
    MemorySize: 512
    Timeout: 20
Outputs:
  CreateStudyRecordFunction:
    Description: CreatePersonRecord Lambda Function ARN
    Value:
      Fn::GetAtt:
      - CreatePersonRecordFunction
      - Arn
  GetStudyRecordsByIsConsumedFunction:
    Description: GetPersonRecordsByNameCpf Lambda Function ARN
    Value:
      Fn::GetAtt:
      - GetPersonRecordsByNameCpfFunction
      - Arn
  GetStudyRecordsByPeriodFunction:
    Description: GetPersonRecordsByPeriod Lambda Function ARN
    Value:
      Fn::GetAtt:
      - GetPersonRecordsByPeriodFunction
      - Arn
  GetStudyRecordsByTagFunction:
    Description: GetPersonRecordsByNameGener Lambda Function ARN
    Value:
      Fn::GetAtt:
      - GetPersonRecordsByNameGenerFunction
      - Arn
Resources:
  CreateStudyRecordFunction:
    Properties:
      CodeUri: s3://aws-sam-fiap-deployt/896a140ec24d1c84f917b82d6bdddd3f
      Events:
        CreateStudyRecord:
          Properties:
            Method: post
            Path: /person
          Type: Api
      Handler: br.edu.fiap.serverlessarchitecture.handler.CreatePersonRecord::handleRequest
      Runtime: java8
    Type: AWS::Serverless::Function
  GetStudyRecordsByIsConsumedFunction:
    Properties:
      CodeUri: s3://aws-sam-fiap-deployt/896a140ec24d1c84f917b82d6bdddd3f
      Events:
        GetStudyRecordsByIsConsumed:
          Properties:
            Method: get
            Path: /person/{name}/findByNameCpf
            RequestParameters:
            - method.request.querystring.cpf
          Type: Api
      Handler: br.edu.fiap.serverlessarchitecture.handler.GetPersonRecordsByNameCpf::handleRequest
      Runtime: java8
    Type: AWS::Serverless::Function
  GetStudyRecordsByPeriodFunction:
    Properties:
      CodeUri: s3://aws-sam-fiap-deployt/896a140ec24d1c84f917b82d6bdddd3f
      Events:
        GetStudyRecordsByPeriod:
          Properties:
            Method: get
            Path: /person/{name}/findByPeriod
            RequestParameters:
            - method.request.querystring.starts
            - method.request.querystring.ends
          Type: Api
      Handler: br.edu.fiap.serverlessarchitecture.handler.GetPersonRecordsByPeriod::handleRequest
      Runtime: java8
    Type: AWS::Serverless::Function
  GetStudyRecordsByTagFunction:
    Properties:
      CodeUri: s3://aws-sam-fiap-deployt/896a140ec24d1c84f917b82d6bdddd3f
      Events:
        GetStudyRecordsByTag:
          Properties:
            Method: get
            Path: /person/{name}/findByNameGener
            RequestParameters:
            - method.request.querystring.gener
          Type: Api
      Handler: br.edu.fiap.serverlessarchitecture.handler.GetPersonRecordsByNameGener::handleRequest
      Runtime: java8
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
